# Generated by Django 3.1.4 on 2020-12-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
